apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalog
  template:
    metadata:
      labels:
        app: catalog
    spec:
      containers:
        - name: catalog
          image: ${AWS_ECR_URL}/catalog-service:${CATALOG_TAG}
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: catalog-service-${CATALOG_TAG}
spec:
  selector:
    app: catalog
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP