apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-deployment-${CATALOG_SERV}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: catalog
      version: ${CATALOG_SERV}
  template:
    metadata:
      labels:
        app: catalog
        version: ${CATALOG_SERV}
    spec:
      containers:
        - name: catalog
          image: ${AWS_ECR_URL}/catalog-service:${CATALOG_TAG}
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: catalog-service-${CATALOG_SERV}
spec:
  selector:
    app: catalog
    version: ${CATALOG_SERV}
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP