apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment-${FRONTEND_SERV}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
      version: ${FRONTEND_SERV}
  template:
    metadata:
      labels:
        app: frontend
        version: ${FRONTEND_SERV}
    spec:
      containers:
        - name: frontend
          image: ${AWS_ECR_URL}/frontend-service:${FRONTEND_TAG}
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service-${FRONTEND_SERV}
spec:
  selector:
    app: frontend
    version: ${FRONTEND_SERV}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP