apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-deployment-${ORDER_SERV}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order
  template:
    metadata:
      labels:
        app: order
    spec:
      containers:
        - name: order
          image: ${AWS_ECR_URL}/order-service:${ORDER_TAG}
          ports:
            - containerPort: 8080
          env:
            - name: CUSTOMER_SERVICE_HOST
              value: 'customer-service-${CUSTOMER_SERV}'
            - name: CUSTOMER_SERVICE_PORT
              value: "8080"
            - name: CATALOG_SERVICE_HOST
              value: 'catalog-service-${CATALOG_SERV}'
            - name: CATALOG_SERVICE_PORT
              value: "8080"
---
apiVersion: v1
kind: Service
metadata:
  name: order-service-${ORDER_SERV}
spec:
  selector:
    app: order
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP