name: Build and Push All

on:
  workflow_dispatch:

jobs:
  build-push-all:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source-repo
        uses: actions/checkout@v3
        with:
          repository: knakatasf/microservice-source
          token: ${{ secrets.ACCESS_TOKEN }}
          path: source-repo
          fetch-depth: 0
          tags: true

      - name: Build all images
        run: |
          set -e
          cd source-repo
          for svc in frontend-service catalog-service customer-service order-service; do
            echo "🔨 Building $svc..."
            docker build --no-cache --platform linux/amd64 -t $svc ./\$svc
          done

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token:     ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region:            us-east-1

      - name: Login to ECR
        run: |
          aws ecr get-login-password --region us-east-1 \
            | docker login --username AWS --password-stdin ${{ secrets.AWS_ECR_URL }}

      - name: Push all images
        run: |
          set -e
          cd source-repo
          LATEST_VERSION=$(git describe --tags --abbrev=0)
          IMAGE_TAG=$LATEST_VERSION-qa-(date + '%Y%m%d')
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV
          for svc in frontend-service catalog-service customer-service order-service; do
            IMAGE=${{ secrets.AWS_ECR_URL }}/$svc:$IMAGE_TAG
            echo "📦 Tagging $svc → $IMAGE"
            docker tag $svc $IMAGE
            docker push $IMAGE
          done

      - name: Trigger “promote-release” in infra repo
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.TOKEN }}
          repository: knakatasf/microservice-infra
          event-type: launch-qa-ec2
          client-payload: |
            {
              "image_tag": "${{ env.IMAGE_TAG }}"
            }