name: Build and Push

on:
  workflow_dispatch:
    inputs:
      version:
        description: "New Versioning e.g. v1.2.0"
        required: true

jobs:
  detect:
    runs-on: ubuntu-latest
    outputs:
      frontend:  ${{ steps.filter.outputs.frontend }} # This will be true/false after filtering
      catalog:   ${{ steps.filter.outputs.catalog }}
      customer:  ${{ steps.filter.outputs.customer }}
      order:     ${{ steps.filter.outputs.order }}
    steps:
      - name: Checkout infra repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Checkout microservice source
        uses: actions/checkout@v3
        with:
          repository: knakatasf/microservice-source
          token: ${{ secrets.ACCESS_TOKEN }}
          path: source-repo
          fetch-depth: 0

      - id: filter
        uses: dorny/paths-filter@v3
        with:
          filters: |
            frontend:
              - 'source-repo/frontend-service/**'
            catalog:
              - 'source-repo/catalog-service/**'
            customer:
              - 'source-repo/customer-service/**'
            order:
              - 'source-repo/order-service/**'   

  build:
    needs: detect
    runs-on: ubuntu-latest
    env:
      AWS_ECR_URL: ${{ secrets.AWS_ECR_URL }}
    steps:
      - uses: actions/checkout@v3

      - name: Compute QA_TAG
        id: compute_tag
        run: |
          DATE=$(date +%Y%m%d)
          QA_TAG="v${{ github.event.inputs.version }}-qa-${DATE}"
          echo "QA_TAG=$QA_TAG" >> $GITHUB_ENV

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: us-east-1
          aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token:     ${{ secrets.AWS_SESSION_TOKEN }}

      - name: Login to ECR
        run: |
          aws ecr get-login-password --region us-east-1 \
            | docker login --username AWS --password-stdin $AWS_ECR_URL

      - name: Build & Push changed microservices
        run: |
          # Initialize an empty array to collect changed services
          CHANGED_LIST=()
      
          # Pair each detect flag with its service name
          CHANGED=(
            ${{ needs.detect.outputs.frontend }}:frontend-service
            ${{ needs.detect.outputs.catalog  }}:catalog-service
            ${{ needs.detect.outputs.customer }}:customer-service
            ${{ needs.detect.outputs.order    }}:order-service
          )
      
          for entry in "${CHANGED[@]}"; do
            IFS=':' read changed svc <<< "$entry"
            if [ "$changed" = "true" ]; then
              echo "🔨 Building $svc → $AWS_ECR_URL/$svc:$QA_TAG"
              docker build --platform linux/amd64 \
                -t $AWS_ECR_URL/$svc:$QA_TAG "$svc"
              docker push $AWS_ECR_URL/$svc:$QA_TAG
              
              # Append the service name (quoted) to the JSON list
              CHANGED_LIST+=("\"$svc\"")
            fi
          done
      
          # Now CHANGED_LIST might look like: ("\"frontend-service\"" "\"order-service\"")
          # Convert it into a JSON array string and export for downstream use
          echo "CHANGED_SERVICES=[${CHANGED_LIST[*]}]" >> $GITHUB_ENV

      - name: Dispatch deploy-qa
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: knakatasf/microservice-infra
          event-type: deploy-qa
          client-payload: |
            {
              "qa_tag":          "${{ env.QA_TAG }}",
              "changed_services": ${{ env.CHANGED_SERVICES }}
            }